
import inventorycontrol.Inventory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devin
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        //show_inventory();
    }
    //viewing
    public ArrayList<Inventory> productList(){
        ArrayList<Inventory> productList = new ArrayList<>();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String URL = "jdbc:mysql://localhost:3306/products";
            Connection conn = DriverManager.getConnection(URL, "root", "Gortoonforleeway232");
            String SQL = "SELECT * FROM inventory_products";
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM inventory_products");
            ResultSet rs = pst.executeQuery(SQL);
            Inventory inventory;
            
            while(rs.next()){
                inventory = new Inventory(rs.getInt("productID"), rs.getString("productName"), rs.getInt("stock"), rs.getFloat("price"), rs.getString("productCategory"));
                productList.add(inventory);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   
        return productList;
    }
    
    public ArrayList<Inventory> searchProduct(){
       ArrayList<Inventory> searchProduct = new ArrayList<>();
       
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           String URL = "jdbc:mysql://localhost:3306/products";
           Connection conn = DriverManager.getConnection(URL, "root", "Gortoonforleeway232");
           String SQL = "SELECT * FROM inventory_products WHERE productID =?";
           PreparedStatement pst = conn.prepareStatement("SELECT * FROM iventory_products WHERE productID = ?");
           ResultSet rs = pst.executeQuery(SQL);
           Inventory inventory;
           
           while(rs.next()){
               inventory = new Inventory(rs.getInt("productID"), rs.getString("productName"), rs.getInt("stock"), rs.getFloat("price"),rs.getString("productCategory"));
               searchProduct.add(inventory);
           }
       }catch(Exception e){
           System.out.println(e);
       }
        
        return searchProduct;
    }
    
    public void show_inventory(){
        ArrayList<Inventory> list = productList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Inventory.getModel();
        Object[] row = new Object[5];
        for(int i = 0; i<list.size();i++){
            row[0] = list.get(i).getProductID();
            row[1] = list.get(i).getProductName();
            row[2] = list.get(i).getStock();
            row[3] = list.get(i).getPrice();
            row[4] = list.get(i).getCategory();
            model.addRow(row);
        }
    }
    
    public void searchInventory(){
        ArrayList<Inventory> search = searchProduct();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Inventory.getModel();
        Object[] row = new Object[5];
        for(int i = 0; i<search.size();i++){
            row[0] = search.get(i).getProductID();
            row[1] = search.get(i).getProductName();
            row[2] = search.get(i).getStock();
            row[3] = search.get(i).getPrice();
            row[4] = search.get(i).getCategory();
            model.addColumn(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Inventory = new javax.swing.JTable();
        viewInventory = new javax.swing.JButton();
        productID = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        productCat = new javax.swing.JTextField();
        searchInventory = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();

        jMenu1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iventory Control Menu");
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jTable_Display_Inventory.setBorder(new javax.swing.border.MatteBorder(null));
        jTable_Display_Inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "productID", "productName", "stock", "price", "productCategory"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Inventory);

        viewInventory.setText("View All");
        viewInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewInventoryMouseClicked(evt);
            }
        });

        productID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDActionPerformed(evt);
            }
        });

        productName.setText("\n");

        searchInventory.setText("Search");
        searchInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInventoryActionPerformed(evt);
            }
        });
        searchInventory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchInventoryKeyReleased(evt);
            }
        });

        addProduct.setText("Add");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        jButton4.setText("Update");

        jLabel1.setText("Product ID");

        jLabel2.setText("Product Name");

        jLabel3.setText("Stock");

        jLabel4.setText("Price");

        jLabel5.setText("Product Category");

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewInventory)
                        .addGap(137, 137, 137)
                        .addComponent(addProduct)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4)
                        .addGap(35, 35, 35)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(searchInventory))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productID, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productCat, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInventory)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productCat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProduct)
                    .addComponent(viewInventory)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(40, 40, 40))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void viewInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInventoryMouseClicked
        
       
        
        show_inventory();
        
        
       /* Inventory inv = new Inventory();
       
        try{
        inv.viewInventory();
        }catch(Exception e){
            System.out.println(e);
        }*/
    }//GEN-LAST:event_viewInventoryMouseClicked

    private void searchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInventoryActionPerformed
        
        
        
       // searchInventory();
       /* Inventory inv = new Inventory();
       try{
        inv.searchInventory();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }*/
    }//GEN-LAST:event_searchInventoryActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductActionPerformed

    private void searchInventoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInventoryKeyReleased
      
       /* try{
            Class.forName("com.jdbc.mysql.cj.Driver");
            String URL = "jdbc:mysql://localhost:3306;products";
            Connection conn = DriverManager.getConnection(URL, "root", "Gortoonforleeway232");
            String SQL ="SELECT * FROM inventory_products WHERE productID = ' '";
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.setString(1, txt_search.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String add1= rs.getString("productID");
                productID.setText(add1);
                String add2 = rs.getString("productName");
                productName.setText(add2);
                String add3 = rs.getString("stock");
                stock.setText(add3);
                String add4 = rs.getString("price");
                price.setText(add4);
                String add5 = rs.getString("productCategory");
                productCat.setText(add5);
            }
        }catch(Exception e){
            System.out.println(e);
        }   */   
        
        
        
        
    }//GEN-LAST:event_searchInventoryKeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String URL = "jdbc:mysql://localhost:3306/products";
            Connection conn = DriverManager.getConnection(URL, "root", "Gortoonforleeway232");
            String SQL ="SELECT * FROM inventory_products WHERE productID = ?";
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.setString(1, txt_search.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String add1= rs.getString("productID");
                productID.setText(add1);
                String add2 = rs.getString("productName");
                productName.setText(add2);
                String add3 = rs.getString("stock");
                stock.setText(add3);
                String add4 = rs.getString("price");
                price.setText(add4);
                String add5 = rs.getString("productCategory");
                productCat.setText(add5);
            }
        }catch(Exception e){
            System.out.println(e);
        }      
    }//GEN-LAST:event_txt_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Inventory;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productCat;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productName;
    private javax.swing.JButton searchInventory;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton viewInventory;
    // End of variables declaration//GEN-END:variables
}
